### ISSUE TITLE
jar丢失

### ISSUE THREAD

**Issue by illsion** [andyslin/autumn-workflow#1]
根据pom的仓库 下载不到想要的jar

**Comment by andyslin** [comment]
pom.xml的仓库是内部仓库，每次提交的时候都修改比较麻烦，我没有修改，这个配置只影响组件发布，不影响组件依赖的下载。
要运行的话，可以把autumn-utils这个项目也下载，然后明确指定autumn-utils的版本(0.0.1-SNAPSHOT)，或者把autumn-bom里面的所有项目都下载到本地。
